version: "3"
networks:
    redprincipal:
        driver: bridge

services:
    marion1:
        image: marion:1
        container_name: marion1
        ports:
          - "8081:80"
        networks:
            - redprincipal

    marion2:
      image: marion:2
      container_name: marion2
      ports:
        - "8082:80"
      networks:
            - redprincipal

    load_balance:
        image: nginx:latest
        ports:
            - "1000:80"
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        networks:
            - redprincipal